# 同一次元オブザーバー

次のシステムについて考える。これのオブザーバー極を-3, -2±jとしてオブザーバーゲインを設計する ([2]の7章演習問題の問1を参照)。
$$
\dot{x} = \left[
\begin{matrix} 
-1 & 0 & 2 \\ 
1 & -1 & 0 \\ 
0 & 1 & -2
\end{matrix}
\right]x + 
\left[
\begin{matrix} 
0 & 1 \\ 
0 & 0 \\
1 & 0
\end{matrix}
\right]u, \:
y = \left[
\begin{matrix} 
1 & 0 & 1
\end{matrix}
\right]x
$$

In [1]:
import numpy as np
from control.matlab import *
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
A = '-1 0 2; 1 -1 0; 0 1 -2'
B = '0 1; 0 0; 1 0'
C = '1 0 1'
D = '0 0'
P = ss(A, B, C, D)

In [15]:
print(P)

A = [[-1  0  2]
 [ 1 -1  0]
 [ 0  1 -2]]

B = [[0 1]
 [0 0]
 [1 0]]

C = [[1 0 1]]

D = [[0 0]]



In [44]:
np.linalg.eigvals(P.A)

array([-6.32980743e-17+0.j, -2.00000000e+00+1.j, -2.00000000e+00-1.j])

### 可観測性の確認
正則であるため問題なし。

In [47]:
Uo = obsv(P.A, C)
print('Uo = \n', Uo)
print('det(Uo) =', np.linalg.det(Uo))
print('rank(Uo) = ', np.linalg.matrix_rank(Uo))

Uo = 
 [[ 1  0  1]
 [-1  1  0]
 [ 2 -1 -2]]
det(Uo) = -3.0000000000000004
rank(Uo) =  3


### オブザーバーゲインを求める
アッカーマンのアルゴリズムを利用する。

In [17]:
observer_poles = [-3, -2+1j, -2-1j]
L = -acker(P.A.T, P.C.T, observer_poles).T

In [18]:
print(L)

[[-2.]
 [-2.]
 [-1.]]


In [19]:
np.linalg.eigvals(P.A+L*P.C)

array([-2.+1.j, -2.-1.j, -3.+0.j])

## 参考文献
[1] 南裕樹 (2019) 『Pythonによる制御工学入門』 オーム社  
[2] 吉川恒夫・井村順一 (1994) 現代制御理論 昭晃堂  